[package]
name = "Wikimapia"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
bzip2 = "0.5.0"
lazy_static = "1.5.0"
quick-xml = "=0.24.1"
regex = "1.11.1"
reqwest = { version = "0.12.11", features = ["blocking"] }
rusqlite = "0.32.1"
scraper = "0.22.0"
